### ISSUE TITLE
AttributeError: type object _ has no attribute 'model'

### ISSUE THREAD

**Issue by urlsangel** [takeflight/wagtailmodelchooser#1]
Hi there

I'm getting this error when trying to decorate a simple model:

```
File "/usr/src/app/common/models.py", line 52, in <module>
web_1            |     class Location(models.Model):
File "/usr/local/lib/python3.5/site-packages/wagtailmodelchooser/__init__.py", line 8, in register_chooser
web_1            |     self.choosers[chooser.model] = chooser()
web_1            | AttributeError: type object 'Location' has no attribute 'model'
```

Using this code to define the model:

```
from django.db import models
from wagtailmodelchooser import register_model_chooser

@register_model_chooser
class Location(models.Model):

    city = models.CharField(
        max_length=140,
    )

    def __str__(self):
        return self.city
```

Any idea what I'm doing wrong?

Thanks,

Russell.

**Comment by timheap** [comment]
@urlsangel This was a problem with the README. It should have said to use `@register_simple_model_chooser`. I've reworked `@register_model_chooser` somewhat so it accepts both models and Chooser classes. Chooser classes are not covered in the documentation yet, sorry, but you can see how to use all the options [in the tests](https://github.com/takeflight/wagtailmodelchooser/blob/master/tests/app/models.py). Specifically, the interesting bits are:

```python
@register_model_chooser(icon='user')
class Author(models.Model, index.Indexed):
    ...

class Book(models.Model):
    ...

@register_model_chooser
class BookChooser(Chooser):
    model = Book
    icon = 'book'
```

**Comment by urlsangel** [comment]
Hi Tim

Cheers for responding so quick, that's compiled for me now.

Thanks,

Russell.
