### ISSUE TITLE
SyntaxError with Python 3.4

### ISSUE THREAD

**Issue by loicteixeira** [takeflight/wagtailmodelchooser#4]
Installing this module and adding it to the `INSTALLED_APPS` produce this error:
```
  File "~/.virtualenvs/.../lib/python3.4/site-packages/wagtailmodelchooser/utils.py", line 40
    return lambda last: func(*args, last, **kwargs)
                                               ^
SyntaxError: only named arguments may follow *expression
```

Will the package require Python 3.5, given that Wagtail itself still supports Python 2?

**Comment by timheap** [comment]
We develop for Python 3 at Takeflight, so Python 2 compatibility is not high on our list of priorities until someone requires it. The conversion was fairly simple in this case though, and gave me an excuse to actually write some tests.

Python 2 and 3.4 compatibility has been released in version 0.3.0.
